# GitHub Sponsors configuration
# Uncomment and configure if you set up sponsorship

# github: [Fizzolas]
# patreon: voiceclone-studio
# open_collective: voiceclone-studio
# ko_fi: voiceclonestudio
# custom: ["https://paypal.me/voiceclonestudio", "https://buymeacoffee.com/voiceclonestudio"]